<?php
include('header.php');
?>

<div class="container-fluid content_container">
	<div class="about">
		<div class="text">
			<h1>Terms & Conditions</h1>
			<div class="line"></div>
		</div>
	</div>
	<div class="content">
		<div class="content_header">
			<h4>Indian handicrafts online shopping store in India</h4>
			<h4>Madefru- Made For You</h4>
		</div>
		<span class="green_text">
			Terms And Conditions Relating To Your Use Of Madefru.com
		</span>
		<ul>
			<li>
				<p>At the time of using the website of Madefru, it is your responsibility to maintain the confidentiality of your account and password. Not only that, keeping the access to your computer restricted is important to prevent unauthorised access to your account. You also agree to accept responsibility regarding every single activity that will occur under your account which you have created on your own and the password that you have generated by yourself. </p>
			</li>
			<li>
				<p>You have to take all the necessary steps to ensure that the password is kept confidential and secure.</p>
			</li>
			<li>
				<p>In case if you think that someone has your password or it has been leaked by mistake, then you should inform us immediately. We will guide and help you during such circumstances.</p>
			</li>
			<li>
				<p>Make sure that all the details you provide us during the time of registration or signing up are correct and complete. And in future, it is your responsibility to inform us immediately if you have relocated or want to update any details related to your account.</p>
			</li>
			<li>
				<p>You agree that you will only use your Madefru account on the website to purchase handicraft products only for your personal use and not for resale or any kind of business purposes.</p>
			</li>
			<li>
				<p>In case you wish to order products for any kind of business purposes, it is mandatory for you to please create a business account on Madefru.com/business.</p>
			</li>
			<li>
				<p>Madefru.com is authorized and reserves the right to refuse access to the website, remove or edit content, terminate accounts, etc. at any time without giving any prior notice or informing you.</p>
			</li>
		</ul>
		<span class="green_text">*Terms & conditions applicable.</span>
	</div>
</div>
<div>
	<?php
	include('footer.php');
	?>
</div>